jina-ai/cloud-ops

- .gitignore
- aws/client.py
- aws/enums.py
- aws/excepts.py
- aws/helper.py
- aws/logger.py
- aws/services/cloudformation.py
- aws/services/cloudwatch.py
- aws/services/lambda_.py
- aws/services/ssm.py
- hub_api_deployment/deployment.py
- hub_api_deployment/prepare_lambda.sh
- lambda_handlers/mongoatlas_reader.py
- lambda_handlers/req_mongoatlas_reader.txt
- requirements.txt
- stress_test_trigger/README.MD
- stress_test_trigger/cloud_ymls/cfn-stress-test.yml
- stress_test_trigger/cloud_ymls/ssm-stress-test.yml
- stress_test_trigger/ssm_entrypoint.sh
- stress_test_trigger/trigger_stress_test.py
- Moving aws scripts from stress-test repo.
- Adding capabilities for Lambda function creation/update (to be integrated with CI/CD)
> Repo refactoring + AWS Lambda deployment for Hub APIs

- k8s_example/README.md
- k8s_example/k8s/production/configmap.yaml
- k8s_example/k8s/staging/configmap.yaml
- k8s_example/k8s/test/configmap.yaml
1. add kubectl, minikube, helm in readme.
2. Initialise an empty file structure for project.
> feat: add k8s readme and structure project

- .github/workflows/hub-api-cd.yml
- hubapi/cloud_ymls/apigateway.yml
- hubapi/deployment.py
- lambda_handlers/docker_auth.py
- lambda_handlers/tests/unit/test_docker_auth.py
> feat: add handler for docker auth

- backup/delete-api/mongodb_endpoints/delete-api/apigateway-delete.yml
- backup/delete-api/mongodb_endpoints/delete-api/deployment-delete.py
- backup/delete-api/mongodb_endpoints/delete-api/hub-api-cd-delete.yml
- backup/delete-api/mongodb_endpoints/delete-api/hubapi_delete.py
- backup/delete-api/mongodb_endpoints/tests/unit/test_hubapi_delete.py
> feat: add delete api for mongodb

- scripts/deb-systemd.sh
use `usr/local/jina/tmp` as `$TMPDIR` when `pip install <pkgs>`
> Fix pip pkgs

- stress-example/image/requirements.txt
- stress-example/text/requirements.txt
> fix: use git for pip installation

- scripts/deb-systemd.sh
- stress_test_trigger/cloud_ymls/daemon-stress-test-infra.yml
> https://pip.pypa.io/en/stable/cli/pip_install/#examples
> https://github.com/jina-ai/jina/issues/3247
> chore(pip): via git

- .github/workflows/docsbot-evaluate.yml
add evaluation workflow for DocsQA
> feat: datasets evaluation

- .github/workflows/docsqa-batch-deploy.yml
resolved https://github.com/jina-ai/docsQA/issues/709
> feat: update the batch update script

- .github/workflows/docsqa-publish-executors.yml
closes https://github.com/jina-ai/docsQA/issues/707
> feat: add docsqa publish executors workflow

- .github/workflows/docsqa-batch-deploy.yml
fix the batch deployment script
> fix: fix the batch deployment script

- .github/workflows/docsqa-publish-executors.yml
For debugging the Hubble push hang issue.
> ci: use verbose mode for wolf.batch.flow_normalize

- .github/workflows/docsqa-publish-executors.yml
adapt to https://github.com/jina-ai/docsQA/pull/729
> feat: adapt to docsqa PR729

- .github/workflows/docsqa-publish-executors.yml
> ci: add jcloud debugging info

- .github/workflows/docsqa-publish-executors.yml
> feat: upload to s3

- .github/workflows/docsqa-batch-deploy.yml
- .github/workflows/docsqa-publish-executors.yml
- .github/workflows/docsqa-serverless-deploy.yml
> feat: adapt to the logger

- .github/workflows/docsqa-batch-deploy.yml
fix the bug in passing env variables
> fix: fix the bug

- .github/workflows/docsqa-batch-deploy.yml
> fix: add the missing token

- .github/workflows/docsqa-reindex-wordlift.yml
> feat: add wordlift specific logic

- .github/workflows/docsqa-reindex-wordlift.yml
> feat: add wordlift indexing script

- .github/workflows/docsqa-reindex-wordlift.yml
fix the wordlift bug on https://jinaai.slack.com/archives/C02F0GBPXAP/p1656691130125859?thread_ts=1656683894.195169&cid=C02F0GBPXAP
> fix wordlift bug

- .github/workflows/docsqa-update-repos.yml
resolved https://github.com/jina-ai/docsQA/issues/851
> feat: add reindex GHA

- .github/workflows/docsqa-update-repos.yml
Update DocsQA projects every Monday at 2 AM GMT
> feat: cron auto update

- .github/workflows/docsqa-update-repos.yml
> fix: disable force reindex

- .github/workflows/docsqa-update-repos.yml
fix docsqa missing logger setting
> fix: fix docsqa missing logger setting

- .github/workflows/docsqa-publish-executors.yml
fix docsqa publish to jcloud 0.2
> fix: fix docsqa publish to jcloud 0.2

- .github/workflows/docsqa-batch-deploy.yml
> fix: add jina auth token
